name: voice-digit-scanner
channels:
  - anaconda
  - conda-forge
  - pytorch
  - pypi

dependencies:
  - python=3.9.18
  - tqdm
  - PyYAML
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pillow
  - opencv
  - pyaudio
  - pyqt
  - tensorboardX
  - librosa
  - xdboost
  - catboost
  - pytorch
  - torchvision
  - torchaudio
  - pyaudio
  - pydub
