arch: 
    lite:
      layers:
        - type: Conv2d
          in_channels: 1
          out_channels: 8
          kernel_size: 5
          stride: 2
          padding: 2
        - type: ReLU
        - type: BatchNorm2d
          num_features: 8

        - type: Conv2d
          in_channels: 8
          out_channels: 16
          kernel_size: 3
          stride: 2
          padding: 1
        - type: ReLU
        - type: BatchNorm2d
          num_features: 16

        - type: Conv2d
          in_channels: 16
          out_channels: 32
          kernel_size: 3
          stride: 2
          padding: 1
        - type: ReLU
        - type: BatchNorm2d
          num_features: 32
        
        - type: Conv2d
          in_channels: 32
          out_channels: 64
          kernel_size: 3
          stride: 2
          padding: 1
        - type: ReLU
        - type: BatchNorm2d
          num_features: 64
        
        - type: AdaptiveAvgPool2d
          output_size: 1
        
        - type: Flatten

        - type: Linear
          in_features: 64
          out_features: 10
          

      optimizer:
        name: Adam
        lr: 0.001

        # name: AdamW
        # weight_decay: 0.001
        # betas:
        #   - 0.9 # beta1
        #   - 0.999 # beta2
        # lr: 0.005
        
      scheduler:
        name: OneCycleLR
        max_lr: 0.001
        anneal_strategy: linear

      loss: CrossEntropyLoss
        
      metrics:
        - accuracy
        - roc_auc
        - precision
        - recall

      epochs: 10
    
    