arch: 
    lite:
      layers:
        - type: Conv2d
          in_channels: 1
          out_channels: 16
          kernel_size: 5
          stride: 1
          padding: 2
        - type: ReLU
        - type: MaxPool2d
          kernel_size: 2
          stride: 2
        - type: Conv2d
          in_channels: 16
          out_channels: 32
          kernel_size: 5
          stride: 1
          padding: 2
        - type: ReLU
        - type: MaxPool2d
          kernel_size: 2
          stride: 2
        - type: Flatten
        - type: Linear
          in_features: 188416
          out_features: 2944
        - type: ReLU
        - type: Linear
          in_features: 2944
          out_features: 10
          

      optimizer:
        name: AdamW
        weight_decay: 0.001
        betas:
          - 0.9 # beta1
          - 0.999 # beta2
        lr: 0.005
        
      scheduler:
        name: OneCycleLR
        max_lr: 0.01
        anneal_strategy: linear
        # steps_per_epoch: 100

      loss: CrossEntropyLoss
        
      metrics:
        - accuracy
        - roc_auc
        # - log_loss
        - precision
        - recall

      epochs: 30
    
    