random_seed: 42
device: mps # cpu, cuda, mps

tasks:
  train:
    data:
      - type: dir
        name: original
        path: data

        split: True
        test_size: 0.05
        val_size: 0.05
        
        shuffle: True

        augmentation: 
          classes: 
            - 4
            - 5
            - 6
            - 7
          augmentation:
            - name: change_volume
              param:
                level: 2
            - name: change_tonalities
              param:
                n_steps: 2
            - name: add_noise
              param: 
                type: pink
                level: 0.25

        path_to_csv: csv_data/original

    dataset:
      paths:
        train: 
        - csv_data/original/train.csv
        val: 
        - csv_data/original/val.csv
        test: 
        - csv_data/original/test.csv

    dataloader:
        batch_size: 16    
        num_workers: 2

    model: codes/models/model_cnn.yml

    results:
      model_object: results/model_v1.pth

    plots: 
      # spectra: 
      #   refer: plots/spectra
      #   num: 5
      loss: plots/loss.png

      accuracy: plots/metrics/accuracy.png
      # precision: plots/metrics/precision.png
      # recall: plots/metrics/recall.png
      # f1: plots/metrics/f1.png
      # roc: plots/metrics/roc.png
        